### PR TITLE
Branch fix add to class command and add tests for command and parser

### LINKED ISSUE #183: [PE-D] No error message/ Cannot press enter for improper addtoclass parameters
When trying to enter the input as shown, cannot press enter & no error message sent.

-------------
Labels: `severity.High` `type.FeatureFlaw`
original: BenjaminTan99/ped#4

### LINKED ISSUE #184: [PE-D] Incorrect error for addtoclass
addtoclass CLASS_INDEX STUDENT_INDEX...

The class exists, but the student does not exist. However, the error does not match the test case.

-------------
Labels: `type.FeatureFlaw` `severity.Medium`
original: FergusMok/ped#3

### LINKED ISSUE #186: [PE-D] addtoclass Wrong error message
Wrong error message, should be student index provided is invalid.

-------------
Labels: `severity.Medium` `type.FeatureFlaw`
original: BenjaminTan99/ped#5

### LINKED ISSUE #187: [PE-D] Incorrect error for addtoclass, existing students
Student 9,10, 11 is Warren, John, and John2.

However, the error only tells me of Warren, and not all 3 students.

-------------
Labels: `type.FunctionalityBug` `severity.Medium`
original: FergusMok/ped#4

### LINKED ISSUE #222: [PE-D] Same issue as addtoclass command
Same issue as #5, program will clash silently when invalid index is given for addtoclass command

-------------
Labels: `severity.Medium` `type.FeatureFlaw`
original: chowRuiYan/ped#9

### PR DESCRIPTION
**Pull request by softmagnet**
close #187 
close #186 
close #184 
close #183 
close #222

### CODE REVIEW

File: src/main/java/seedu/address/model/person/Name.java [hunk 1]
```diff
@@ -34,6 +34,10 @@ public Name(String name) {
         fullName = name;
     }
 
+    public String getFullName() {
+        return fullName;
+    }
+
```
Comment (Ongzl) [inline src/main/java/seedu/address/model/person/Name.java:40]: i don't think this is necessary? since fullname is public already

File: src/main/java/seedu/address/model/tuitionclass/TuitionClass.java [hunk 2]
```diff
@@ -113,6 +114,10 @@ public void addStudent(Name name) {
         studentNameList.add(name);
     }
 
+    public void addAllStudents(Name... names) {
+        studentNameList.addAll(Arrays.asList(names));
+    }
+
```
Comment (Ongzl) [inline src/main/java/seedu/address/model/tuitionclass/TuitionClass.java:120]: you want to just overload addStudentList to also accept List<Name> so that don't have so many methods to keep track of?

**Review by Ongzl — COMMENTED** [review]
otherwise LGTM

File: src/main/java/seedu/address/model/person/Name.java (hunk 1 above)
Comment (softmagnet) [reply src/main/java/seedu/address/model/person/Name.java:40]: hmm but why is it public though

File: src/main/java/seedu/address/model/tuitionclass/TuitionClass.java (hunk 2 above)
Comment (softmagnet) [reply src/main/java/seedu/address/model/tuitionclass/TuitionClass.java:120]: I think can arh but i think can merge this PR first

File: src/main/java/seedu/address/model/person/Name.java (hunk 1 above)
Comment (Ongzl) [reply src/main/java/seedu/address/model/person/Name.java:40]: from AB3 one thats why got some lines is like getName().fullname
