### PR TITLE
fix issues #216, #195, added 1 testcase for overlapping tuitionclasses

### LINKED ISSUE #195: [PE-D] editclass Invalid error
Gives the wrong error. The correct error should be 'The class index provided is invalid'

-------------
Labels: `type.FunctionalityBug` `severity.Medium`
original: FergusMok/ped#6

### LINKED ISSUE #216: [PE-D] editclass command does not check if timing clashes after edit
Notice how the timings for the first and second class overlap

-------------
Labels: `severity.Medium` `type.FeatureFlaw`
original: houtenteo/ped#6

### PR DESCRIPTION
**Pull request by Ongzl**
resolves #216,
resolves #195

### CODE REVIEW

File: src/main/java/seedu/address/model/tuitionclass/UniqueClassList.java [hunk 1]
```diff
@@ -165,6 +165,12 @@ public void setClass(TuitionClass target, TuitionClass editedClass) {
         if (!target.isSameClass(editedClass) && contains(editedClass)) {
             throw new DuplicateClassException();
         }
+        //check for overlapping ClassTiming.
+        for (TuitionClass tuitionClass : internalList) {
```
Comment (softmagnet) [inline src/main/java/seedu/address/model/tuitionclass/UniqueClassList.java:169]: the logic for checking overlap is already written in isValidTiming. Using condition 
```
if (!target.isSameClass(editedClass) && !isValidTiming(editedClass)) 
```
would suffice

**Review by softmagnet — CHANGES_REQUESTED** [review]

File: src/main/java/seedu/address/model/tuitionclass/UniqueClassList.java (hunk 1 above)
Comment (Ongzl) [reply src/main/java/seedu/address/model/tuitionclass/UniqueClassList.java:169]: ok thanks

**Comment by s7u4rt99** [comment]
LGTM
